# Generated by Django 2.2.1 on 2019-07-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='toppings_required',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
