# Generated by Django 2.2.1 on 2019-07-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190722_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_topping',
        ),
    ]
