# Generated by Django 2.2.1 on 2019-07-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190722_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menucategory',
            old_name='menu_order',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_category',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.MenuCategory'),
        ),
    ]
